- name: Run NGNINX docker container
  docker_container:
    name: nginx
    image: nginx
    state: started
    restart_policy: unless-stopped
    volumes:
      - /var/log/nginx:/var/log/nginx
      - /etc/nginx/conf.d:/etc/nginx/conf.d
      - /etc/nginx/proxy.conf:/etc/nginx/proxy.conf:ro
    published_ports:
      - 80:80
      - 443:443

- name: Apply NGINX configuration for hashi vault
  template:
    src: vault.conf.j2
    dest: /etc/nginx/conf.d/vault.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart NGINX container

