- name: Create Hashi Vault
  docker_container:
    name: vault
    image: vault:1.3.1
    command: server
    state: started
    restart_policy: unless-stopped
    capabilities:
      - ipc_lock
    volumes:
      - /etc/vault/logs:/vault/logs
      - /etc/vault/file:/vault/file
      - /etc/vault/config:/vault/config
    published_ports:
      - "{{vault_port}}:8200"
    env:
      VAULT_LOCAL_CONFIG: '{"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'

